version: '3.8'
services:
  nginx:
    container_name: sf_nginx
    image: nginx:stable
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    links:
      - gateway
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ../project/gateway/public:/usr/share/nginx/public
      - ./logs/nginx:/var/log/nginx
    networks:
      - sf_network

  gateway:
    container_name: sf_gateway
    build: ./docker/php8_2-service
    image: sf_gateway:0.1
    ports:
      - "8800:8800"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./logs/supervisor/gateway:/var/log/supervisor
      - ../project/gateway/:/var/www/gateway
      - ./supervisor/gateway.conf:/etc/supervisor/conf.d/gateway.conf
      - ./docker/php8_2-service/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      PROJECT_DIR: /var/www/gateway
    working_dir: /var/www/gateway
    networks:
      - sf_network

  mysql:
    container_name: sf_mysql
    image: mysql:8.0.25
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrations/oauth/:/var/migrations
      - sfMysqlServerData:/var/lib/mysql
    networks:
      - sf_network

volumes:
  sfMysqlServerData:
    driver: local

networks:
  sf_network:
    name: sf_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.36.0/24
