---
server.name: kibana
server.host: "0"
server.basePath: '/kibana'
#elasticsearch.url: http://elasticsearch:9200
elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false
